#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy to Github pages

on:
  push:
    #tags:
    #  - v*
    branches:
      - main

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install
    - run: yarn docs

    - run: touch docs/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './docs'
    - name: Deploy docs to GitHub Pages 🚀
      id: deployment
      uses: actions/deploy-pages@v2
